services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "7071:7071" # JMX port
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"  # nodeId@host:port
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      CLUSTER_ID: "S3gBDPSmSPWUi-ijFP5EwQ"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"  # Tek node için 1 yapın
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
      KAFKA_OPTS: "-javaagent:/jmx_prometheus_javaagent.jar=7071:/jmx_config.yml"
    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./monitoring/jmx_prometheus_javaagent.jar:/jmx_prometheus_javaagent.jar
      - ./monitoring/jmx_config.yml:/jmx_config.yml

  weather-production:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      KAFKA_BROKERS: "kafka:9092"
    restart: on-failure
  
  weather-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - kafka
    ports:
      - "8001:8001"
    environment:
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: "weather-data"
      GROUP_ID: "weather-group"
    restart: on-failure

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  prometheus:
    image: prom/prometheus:v2.40.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka

  grafana:
      image: grafana/grafana:9.5.0
      ports:
        - "3000:3000"
      environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - grafana_data:/var/lib/grafana
      depends_on:
        - prometheus
  node-exporter:
      image: prom/node-exporter:latest
      ports:
        - "9100:9100"
      restart: unless-stopped
      volumes:
      - /proc:/host/proc:ro              # Process metrics
      - /sys:/host/sys:ro                # System metrics  
      - /:/rootfs:ro                     # Disk metrics
      command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg
    restart: unless-stopped
volumes:
  kafka_data:
  grafana_data: